# ============================================================
# thermal_analysis.py
#
# Steady-state thermal analysis of Cu target structure
# DOLFINx 0.11.0
#
# Physics:
#   - Heat conduction in copper
#   - Fixed cold-head temperature
#   - Thermal radiation from 300 K vacuum chamber
#   - No gas conduction (vacuum)
#
# Geometry:
#   target.msh generated by Gmsh
#   Geometry unit in Gmsh = mm
# ============================================================

from datetime import datetime
from pathlib import Path

import numpy as np

from mpi4py import MPI
from petsc4py import PETSc

import ufl

from dolfinx import fem
from dolfinx.fem import petsc
from dolfinx.io import gmsh as gmshio
from dolfinx.io import XDMFFile


# ============================================================
# 1. Parameters
# ============================================================

MESH_FILE = "target.msh"
RESULT_DIR = Path(__file__).resolve().parent / "result"

# Physical group IDs defined in target_geometry.py
COPPER_ID = 1
COLD_HEAD_ID = 2
RADIATION_ID = 3


# ------------------------------------------------------------
# Thermal conditions
# ------------------------------------------------------------

# Cold-head temperature [K]
T_COLD = 30.0

# Vacuum chamber / surrounding radiation temperature [K]
T_ENV = 300.0

# Open an interactive 3D temperature view after saving the result.
SHOW_3D = True

# Export at four times the window width and height (16 times the pixels).
PDF_IMAGE_SCALE = 4

# Use the same font size for all figure labels.
VIEW_FONT_SIZE = 14


# ------------------------------------------------------------
# Copper thermal conductivity
#
# First test: constant k
# Later we can replace this by k(T) for cryogenic copper.
# ------------------------------------------------------------

K_CU = 400.0       # W / (m K)


# ------------------------------------------------------------
# Copper surface emissivity
#
# 0.05 = approximate polished copper
# Later this should be adjusted according to surface condition.
# ------------------------------------------------------------

EMISSIVITY = 0.05


# Stefan-Boltzmann constant
SIGMA_SB = 5.670374419e-8   # W / (m^2 K^4)


# ============================================================
# 2. Read Gmsh mesh
# ============================================================

if MPI.COMM_WORLD.rank == 0:
    print()
    print("========================================")
    print(" Thermal FEM analysis")
    print("========================================")
    print(f"Mesh file       : {MESH_FILE}")
    print(f"Cold head       : {T_COLD:.2f} K")
    print(f"Environment     : {T_ENV:.2f} K")
    print(f"Copper k        : {K_CU:.2f} W/(m K)")
    print(f"Emissivity      : {EMISSIVITY:.3f}")
    print("========================================")
    print()
    print("Reading mesh...")


mesh_data = gmshio.read_from_msh(
    MESH_FILE,
    MPI.COMM_WORLD,
    rank=0,
    gdim=3
)

mesh = mesh_data.mesh
cell_tags = mesh_data.cell_tags
facet_tags = mesh_data.facet_tags


# ============================================================
# 3. Convert geometry from mm to m
# ============================================================

# Gmsh geometry was constructed in mm.
# FEM heat equation must use SI units.

mesh.geometry.x[:] *= 1.0e-3


if MPI.COMM_WORLD.rank == 0:
    print("Converted geometry: mm -> m")


# ============================================================
# 4. Check physical groups
# ============================================================

if cell_tags is None:
    raise RuntimeError(
        "No cell tags found in target.msh.\n"
        "Check COPPER physical group in target_geometry.py."
    )

if facet_tags is None:
    raise RuntimeError(
        "No facet tags found in target.msh.\n"
        "Check COLD_HEAD and RADIATION physical groups."
    )


if MPI.COMM_WORLD.rank == 0:

    print()
    print("Physical groups in mesh:")

    for name, group in mesh_data.physical_groups.items():
        print(
            f"  {name:15s}"
            f" dim={group.dim}"
            f" tag={group.tag}"
        )

    print()


# ============================================================
# 5. Function space
# ============================================================

V = fem.functionspace(
    mesh,
    ("Lagrange", 1)
)


# Temperature field
T = fem.Function(V)

T.name = "Temperature"


# Initial guess
#
# Nonlinear radiation requires an initial temperature.
# 100 K is a reasonable starting value for this test.

T.x.array[:] = 100.0
T.x.scatter_forward()


# Test function
v = ufl.TestFunction(V)


# ============================================================
# 6. Integration measures
# ============================================================

dx = ufl.Measure(
    "dx",
    domain=mesh,
    subdomain_data=cell_tags
)

ds = ufl.Measure(
    "ds",
    domain=mesh,
    subdomain_data=facet_tags
)


# ============================================================
# 7. Cold-head boundary condition
# ============================================================

cold_facets = facet_tags.find(COLD_HEAD_ID)


if len(cold_facets) == 0:
    raise RuntimeError(
        "No COLD_HEAD facets found.\n"
        "Check physical surface ID = 2."
    )


fdim = mesh.topology.dim - 1


cold_dofs = fem.locate_dofs_topological(
    V,
    fdim,
    cold_facets
)


bc_cold = fem.dirichletbc(
    PETSc.ScalarType(T_COLD),
    cold_dofs,
    V
)


# ============================================================
# 8. Check radiation surface
# ============================================================

radiation_facets = facet_tags.find(RADIATION_ID)


if len(radiation_facets) == 0:
    raise RuntimeError(
        "No RADIATION facets found.\n"
        "Check physical surface ID = 3."
    )


if MPI.COMM_WORLD.rank == 0:

    print(
        f"Cold-head facets : {len(cold_facets)}"
    )

    print(
        f"Radiation facets : {len(radiation_facets)}"
    )

    print()


# ============================================================
# 9. Material / radiation constants
# ============================================================

k = fem.Constant(
    mesh,
    PETSc.ScalarType(K_CU)
)

epsilon = fem.Constant(
    mesh,
    PETSc.ScalarType(EMISSIVITY)
)

sigma = fem.Constant(
    mesh,
    PETSc.ScalarType(SIGMA_SB)
)

T_env = fem.Constant(
    mesh,
    PETSc.ScalarType(T_ENV)
)


# ============================================================
# 10. Weak form
# ============================================================
#
# Heat conduction:
#
#       div(k grad T) = 0
#
#
# Radiation boundary:
#
#       q_out = epsilon sigma (T^4 - T_env^4)
#
#
# Weak form:
#
# ∫ k grad(T)·grad(v) dV
#
# + ∫ epsilon sigma
#       (T^4 - T_env^4) v dS
#
# = 0
#
# ============================================================


F_conduction = (
    k
    * ufl.dot(
        ufl.grad(T),
        ufl.grad(v)
    )
    * dx(COPPER_ID)
)


F_radiation = (
    epsilon
    * sigma
    * (
        T**4
        - T_env**4
    )
    * v
    * ds(RADIATION_ID)
)


F = (
    F_conduction
    + F_radiation
)


# ============================================================
# 11. Nonlinear solver
# ============================================================

if MPI.COMM_WORLD.rank == 0:
    print("Starting nonlinear thermal solve...")


problem = petsc.NonlinearProblem(
    F,
    T,
    bcs=[bc_cold],
    petsc_options_prefix="thermal_",
    petsc_options={
        # Nonlinear solver
        "snes_type": "newtonls",

        # Backtracking line search
        "snes_linesearch_type": "bt",

        # Convergence
        "snes_rtol": 1.0e-8,
        "snes_atol": 1.0e-9,
        "snes_max_it": 50,

        # Linear solver
        "ksp_type": "preonly",
        "pc_type": "lu",

        # Raise error if convergence fails
        "snes_error_if_not_converged": True,
        "ksp_error_if_not_converged": True,
    },
)


# ============================================================
# 12. Solve
# ============================================================

T_solution = problem.solve()

T_solution.x.scatter_forward()


if MPI.COMM_WORLD.rank == 0:
    print("Thermal solve finished.")


# ============================================================
# 13. Temperature statistics
# ============================================================

local_min = np.min(
    T_solution.x.array
)

local_max = np.max(
    T_solution.x.array
)


global_min = mesh.comm.allreduce(
    local_min,
    op=MPI.MIN
)

global_max = mesh.comm.allreduce(
    local_max,
    op=MPI.MAX
)


if MPI.COMM_WORLD.rank == 0:

    print()
    print("========================================")
    print(" Temperature result")
    print("========================================")

    print(
        f"Minimum temperature : "
        f"{global_min:.3f} K"
    )

    print(
        f"Maximum temperature : "
        f"{global_max:.3f} K"
    )

    print(
        f"Temperature rise    : "
        f"{global_max - global_min:.3f} K"
    )

    print("========================================")
    print()


# ============================================================
# 14. Save result
# ============================================================

if mesh.comm.rank == 0:
    RESULT_DIR.mkdir(parents=True, exist_ok=True)
mesh.comm.barrier()

OUTPUT_FILE = str(
    RESULT_DIR / f"temperature_cold_{T_COLD}K_env_{T_ENV}K.xdmf"
)


with XDMFFile(
    mesh.comm,
    OUTPUT_FILE,
    "w"
) as xdmf:

    xdmf.write_mesh(mesh)

    xdmf.write_function(
        T_solution
    )


if MPI.COMM_WORLD.rank == 0:

    print(
        f"Saved temperature field -> {OUTPUT_FILE}"
    )

    print()


# ============================================================
# 15. View the computed temperature directly (no XDMF reader)
# ============================================================

if SHOW_3D:
    from dolfinx import plot

    # Gather all mesh partitions so rank 0 displays the complete target.
    owned_cells = np.arange(
        mesh.topology.index_map(mesh.topology.dim).size_local,
        dtype=np.int32,
    )
    topology, cell_types, points = plot.vtk_mesh(V, entities=owned_cells)
    partitions = mesh.comm.gather(
        (topology, cell_types, points, T_solution.x.array.real.copy()),
        root=0,
    )

    if mesh.comm.rank == 0:
        try:
            import pyvista as pv
        except ImportError:
            print("3D view requires PyVista: python -m pip install pyvista")
        else:
            print("Opening 3D temperature view...", flush=True)
            pv.global_theme.font.family = "times"
            viewer = pv.Plotter()
            scalar_bar_shown = False
            for topology, cell_types, points, temperatures in partitions:
                if len(cell_types) == 0:
                    continue
                grid = pv.UnstructuredGrid(topology, cell_types, points)
                grid.point_data["Temperature"] = temperatures
                viewer.add_mesh(
                    grid,
                    scalars="Temperature",
                    cmap="coolwarm",
                    smooth_shading=True,
                    split_sharp_edges=True,
                    clim=(float(global_min), float(global_max)),
                    show_scalar_bar=not scalar_bar_shown,
                    scalar_bar_args={
                        "title": "",
                        "font_family": "times",
                        "vertical": True,
                        "position_x": 0.80,
                        "position_y": 0.20,
                        "width": 0.14,
                        "height": 0.60,
                        "title_font_size": VIEW_FONT_SIZE,
                        "label_font_size": VIEW_FONT_SIZE,
                        "n_labels": 4,
                        "fmt": "%.2f",
                    },
                )
                scalar_bar_shown = True
            temperature_title = viewer.add_text(
                "Temperature [K]",
                position=(0.85, 0.83),
                viewport=True,
                font_size=VIEW_FONT_SIZE,
                font="times",
            )
            temperature_title.GetTextProperty().SetJustificationToCentered()
            conditions_text = viewer.add_text(
                f"Cold head: {T_COLD} K | Environment: {T_ENV} K",
                position=(0.02, 0.94),
                viewport=True,
                font_size=VIEW_FONT_SIZE,
                font="times",
            )
            statistics_text = viewer.add_text(
                f"Min: {global_min:.3f} K | Max: {global_max:.3f} K",
                position=(0.02, 0.88),
                viewport=True,
                font_size=VIEW_FONT_SIZE,
                font="times",
            )
            axes = viewer.add_axes(viewport=(0.01, 0.06, 0.25, 0.30))
            axes.SetNormalizedLabelPosition(1.25, 1.25, 1.25)
            for caption in (
                axes.GetXAxisCaptionActor2D(),
                axes.GetYAxisCaptionActor2D(),
                axes.GetZAxisCaptionActor2D(),
            ):
                caption.GetCaptionTextProperty().SetFontFamilyToTimes()
                caption.GetTextActor().SetTextScaleModeToNone()
                caption.GetCaptionTextProperty().SetFontSize(VIEW_FONT_SIZE)
            viewer.view_isometric()
            # Leave space around the target for the header and color legend.
            viewer.camera.zoom(0.85)

            def save_pdf():
                from PIL import Image

                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
                filename = Path(OUTPUT_FILE).with_name(
                    f"{Path(OUTPUT_FILE).stem}_{timestamp}.pdf"
                )
                button_enabled = screenshot_button.GetEnabled()
                button_representation = screenshot_button.GetRepresentation()
                button_visible = button_representation.GetVisibility()
                label_visible = save_label.GetVisibility()
                window_size = tuple(viewer.window_size)
                text_properties = [
                    temperature_title.GetTextProperty(),
                    conditions_text.GetTextProperty(),
                    statistics_text.GetTextProperty(),
                ]
                for scalar_bar in viewer.scalar_bars.values():
                    text_properties.extend([
                        scalar_bar.GetTitleTextProperty(),
                        scalar_bar.GetLabelTextProperty(),
                    ])
                text_properties.extend(
                    caption.GetCaptionTextProperty()
                    for caption in (
                        axes.GetXAxisCaptionActor2D(),
                        axes.GetYAxisCaptionActor2D(),
                        axes.GetZAxisCaptionActor2D(),
                    )
                )
                font_sizes = [prop.GetFontSize() for prop in text_properties]
                try:
                    screenshot_button.SetEnabled(0)
                    button_representation.SetVisibility(0)
                    save_label.SetVisibility(0)
                    viewer.window_size = tuple(int(size * PDF_IMAGE_SCALE) for size in window_size)
                    for prop, size in zip(text_properties, font_sizes):
                        prop.SetFontSize(int(size * PDF_IMAGE_SCALE))
                    viewer.render()
                    image = viewer.screenshot(
                        return_img=True,
                        transparent_background=False,
                        scale=1,
                    )
                    Image.fromarray(image).convert("RGB").save(
                        str(filename), "PDF", resolution=300.0, quality=100,
                        subsampling=0,
                    )
                except OSError as error:
                    print(f"PDF export failed: {error}", flush=True)
                else:
                    print(f"PDF saved -> {filename.resolve()}", flush=True)
                finally:
                    viewer.window_size = window_size
                    for prop, size in zip(text_properties, font_sizes):
                        prop.SetFontSize(size)
                    save_label.SetVisibility(label_visible)
                    screenshot_button.SetEnabled(button_enabled)
                    button_representation.SetVisibility(button_visible)
                    viewer.render()

            def screenshot_button_clicked(checked):
                if checked:
                    screenshot_button.GetRepresentation().SetState(0)
                    viewer.render()
                    save_pdf()

            screenshot_button = viewer.add_checkbox_button_widget(
                screenshot_button_clicked,
                value=False,
                position=(10, 10),
                size=30,
                color_on="royalblue",
                color_off="royalblue",
                background_color="white",
            )
            save_label = viewer.add_text("Save PDF", position=(50, 15), font_size=VIEW_FONT_SIZE, font="times")
            print(
                "Analysis and saving are complete. "
                "Click the blue 'Save PDF' button to save a high-resolution PDF. "
                "The terminal waits until you close the 3D window.",
                flush=True,
            )
            viewer.show(title="Thermal analysis - Temperature [K]")
            print("3D window closed. Finished.", flush=True)
